import { readdirSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

/** The build to capture; a relative path is resolved from the repo root. */
export const dist = path.resolve(
  fileURLToPath(new URL("..", import.meta.url)),
  process.env.VRT_DIST ?? "dist",
);

// Directories under dist that hold no pages of the site.
const excluded = ["~partytown/"];

const files = readdirSync(dist, { recursive: true, withFileTypes: true })
  .filter((entry) => entry.isFile())
  .map((entry) => path.relative(dist, path.join(entry.parentPath, entry.name)))
  .filter((file) => !excluded.some((dir) => file.startsWith(dir)))
  .sort();

/** URL paths of all HTML pages, e.g. "/" and "/posts/". */
export const pages = files
  .filter((file) => file.endsWith(".html"))
  .map((file) => `/${file.replace(/(^|\/)index\.html$/, "$1")}`);

/** OG images generated by the build, relative to dist. */
export const ogImages = files.filter(
  (file) => path.basename(file) === "og.png",
);

if (pages.length === 0) throw new Error(`No HTML pages in ${dist}`);
